### ISSUE TITLE
Repository name is versioned

### ISSUE THREAD

**Issue by reinderien** [JanitorsBucket/tic_tac_toe_NCURSES_v2#2]
The way your repository is named and configured isn't the "Git Way". There are some standard ways to use git and GitHub that will make management of your repository easier.

- Rename your repository from `tic_tac_toe_NCURSES_v2` to `tic_tac_toe_ncurses` or even `tic_tac_toe`. Version information shouldn't be represented in the repository name.
- You should represent the evolution of your code as a continuous series of changes. Either create a new repository (or wipe history from the existing one - this is somewhat involved), commit and push v1, and then commit and push v2. Git will keep your history and you can refer to it later by date time and numerical commit ID.
- You can use git to add named tags for the above two commits.
- After this is done, make your commits smaller and more frequent to have more meaningful history.

Someone has also offered a [pull request](https://github.com/JanitorsBucket/tic_tac_toe_NCURSES_v2/pull/1), which means that they're requesting that you merge their code into yours. There are many different ways to do this. If you want to take his code as a "v3", then you can merge it into master once all of the above are done. If you want to keep the code separately and not in master (for instance, if you want to keep it as a reference but want to write v3 yourself) then you can pull it to a branch in your repository that is not master.

**Comment by an-intrepid-coder** [comment]
Thanks! I'm sorry it took me so long to see this post. I will definitely keep that in mind. Can you recommend a good resource for learning all about git? Learning how to use it on a deep level is next on my list of things to learn,

**Comment by reinderien** [comment]
https://www.git-tower.com/learn/ seems good, or really anything that Google tells you is a free git course or ebook aimed at people new to VCS/SCM.
